### ISSUE TITLE
[Unit Test] Session cannot be started after headers have already been sent

### ISSUE THREAD

**Issue by cbatista8a** [CubaDevOps/flexi#6]
> > Hey again Carlos,
> > I am currently testing the Container.php in domain layer and experiencing some difficulties with session_start(). I load the services from the /Config directory. I am providing you with some screenshots.
> > Do you have a clue where the problem is?
> 
> Usually the error "Session cannot be started after headers have already been sent" is due to some output being sent before the session started, some "echo" perhaps or some test output. Try just running the container test separately to rule out any previous output.

Yes, I tried to resolve it but seems like something in the autoload.php causes it.
If I add 'ob_start();' before the ComposerAutoloader it fixes the problem but not after.
I am not sure how to approach this problem.
![image](https://github.com/CubaDevOps/flexi/assets/160345217/d7262a8f-d16f-400c-ad7a-badbecf19ec0)

_Originally posted by @Qupiter in https://github.com/CubaDevOps/flexi/issues/2#issuecomment-2165030594_

**Comment by cbatista8a** [comment]
I can't reproduce this situation working under Docker container, i implement a little test and it run successfully:
@Qupiter do you can test this example isolated?

```php
<?php

declare(strict_types=1);

namespace CubaDevOps\Flexi\Test\Domain\Classes;

use CubaDevOps\Flexi\Domain\Classes\Container;
use CubaDevOps\Flexi\Domain\Classes\NativeSessionStorage;
use CubaDevOps\Flexi\Infrastructure\Classes\Configuration;
use PHPUnit\Framework\TestCase;
use Psr\Container\ContainerExceptionInterface;
use Psr\Container\NotFoundExceptionInterface;

class ContainerTest extends TestCase
{
    private Container $container;

    /**
     * @throws NotFoundExceptionInterface
     * @throws \ReflectionException
     * @throws ContainerExceptionInterface
     * @throws \JsonException
     */
    public function setUp(): void
    {
        $this->container = new Container();
        $this->container->loadServices('./src/Config/services.json');
    }

    /**
     * @throws \ReflectionException
     * @throws ContainerExceptionInterface
     * @throws NotFoundExceptionInterface
     */
    public function testSessionInstantiation(): void
    {
        $this->assertInstanceOf(Configuration::class, $this->container->get(Configuration::class));
        $this->assertInstanceOf(NativeSessionStorage::class, $this->container->get(NativeSessionStorage::class));
    }
}
```

**Comment by cbatista8a** [comment]
Anyway, I've improved the start of the session a bit.

**Comment by Qupiter** [comment]
> I can't reproduce this situation working under Docker container, i implement a little test and it run successfully: @Qupiter do you can test this example isolated?
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> namespace CubaDevOps\Flexi\Test\Domain\Classes;
> 
> use CubaDevOps\Flexi\Domain\Classes\Container;
> use CubaDevOps\Flexi\Domain\Classes\NativeSessionStorage;
> use CubaDevOps\Flexi\Infrastructure\Classes\Configuration;
> use PHPUnit\Framework\TestCase;
> use Psr\Container\ContainerExceptionInterface;
> use Psr\Container\NotFoundExceptionInterface;
> 
> class ContainerTest extends TestCase
> {
>     private Container $container;
> 
>     /**
>      * @throws NotFoundExceptionInterface
>      * @throws \ReflectionException
>      * @throws ContainerExceptionInterface
>      * @throws \JsonException
>      */
>     public function setUp(): void
>     {
>         $this->container = new Container();
>         $this->container->loadServices('./src/Config/services.json');
>     }
> 
>     /**
>      * @throws \ReflectionException
>      * @throws ContainerExceptionInterface
>      * @throws NotFoundExceptionInterface
>      */
>     public function testSessionInstantiation(): void
>     {
>         $this->assertInstanceOf(Configuration::class, $this->container->get(Configuration::class));
>         $this->assertInstanceOf(NativeSessionStorage::class, $this->container->get(NativeSessionStorage::class));
>     }
> }
> ```

Hmm.. I tried to commit my changes into the new branch but it seems I don't have permissions. Maybe after I push my changes you can have a look at it if it persists.
![image](https://github.com/CubaDevOps/flexi/assets/160345217/27065d19-9993-4c6d-ae27-66b561084a7b)
